/* ═══════════════════════════════════════════════════
   EURO POLO · api/_lib/catalog.js
   Server-side price source of truth.

   The browser may propose WHICH sku and HOW MANY. It may never
   influence the price. Every amount charged is recomputed here
   from data/product-data.json, which is generated by
   data/build_variants.py from the master spreadsheet.
═══════════════════════════════════════════════════ */

// require() (not fs) so Vercel's dependency tracer bundles the JSON.
const productData = require('../../data/product-data.json');

const MAX_QTY_PER_LINE = 20;

/* Build sku -> line info once per cold start. */
let skuIndex = null;

function index() {
  if (skuIndex) return skuIndex;

  skuIndex = new Map();
  const products = Array.isArray(productData) ? productData : (productData.products || []);

  for (const product of products) {
    for (const variant of (product.variants || [])) {
      if (!variant.sku) continue;
      skuIndex.set(String(variant.sku).toUpperCase(), {
        sku:         variant.sku,
        productId:   product.id,
        name:        product.name,
        category:    product.category,
        option1Name: product.option1Name || '',
        option1:     variant.option1 || '',
        option2Name: product.option2Name || '',
        option2:     variant.option2 || '',
        price:       Number(variant.price),
        stock:       Number(variant.stock),
        image:       variant.image || (product.images && product.images.cover) || '',
      });
    }
  }
  return skuIndex;
}

function lookupSku(sku) {
  if (!sku) return null;
  return index().get(String(sku).toUpperCase()) || null;
}

/**
 * Turn a client-supplied cart into trusted server-priced lines.
 *
 * Only `sku` and `qty` are read from the client. Any price, name, total
 * or image the client sends is discarded.
 *
 * @returns {{ lines: Array, subtotal: number } | { error: string }}
 */
function priceCart(clientItems) {
  if (!Array.isArray(clientItems) || clientItems.length === 0) {
    return { error: 'Cart is empty.' };
  }
  if (clientItems.length > 50) {
    return { error: 'Too many items in cart.' };
  }

  const lines = [];
  const seen = new Map();

  for (const raw of clientItems) {
    const sku = raw && raw.sku;
    if (!sku) {
      return { error: 'An item in your cart is missing its product code. Please clear your cart and add items again.' };
    }

    const item = lookupSku(sku);
    if (!item) {
      return { error: `Product code ${sku} is no longer available. Please remove it from your cart.` };
    }

    // Coerce qty to a positive integer — rejects "3abc", 2.5, -1, Infinity.
    const qty = Number(raw.qty);
    if (!Number.isInteger(qty) || qty < 1 || qty > MAX_QTY_PER_LINE) {
      return { error: `Invalid quantity for ${item.name}.` };
    }

    // Merge duplicate lines for the same sku before checking stock.
    const prev = seen.get(item.sku);
    const totalQty = (prev ? prev.qty : 0) + qty;

    if (!Number.isFinite(item.price) || item.price <= 0) {
      return { error: `${item.name} is not currently priced for online purchase.` };
    }
    if (!Number.isFinite(item.stock) || totalQty > item.stock) {
      return { error: `Only ${Math.max(0, item.stock)} left of ${item.name} (${item.option1 || item.sku}).` };
    }

    if (prev) {
      prev.qty = totalQty;
      prev.lineTotal = round2(prev.price * totalQty);
    } else {
      const line = {
        sku:         item.sku,
        productId:   item.productId,
        name:        item.name,
        option1Name: item.option1Name,
        option1:     item.option1,
        option2Name: item.option2Name,
        option2:     item.option2,
        image:       item.image,
        price:       item.price,     // server price — authoritative
        qty:         qty,
        lineTotal:   round2(item.price * qty),
      };
      seen.set(item.sku, line);
      lines.push(line);
    }
  }

  const subtotal = round2(lines.reduce((s, l) => s + l.lineTotal, 0));
  return { lines, subtotal };
}

function round2(n) {
  return Math.round((Number(n) + Number.EPSILON) * 100) / 100;
}

module.exports = { lookupSku, priceCart, round2, MAX_QTY_PER_LINE };
