#!/usr/bin/env node
'use strict';
/* ═══════════════════════════════════════════════════
   EURO POLO · build-journal.js

   Generates, from content/ :
     • one HTML page per article        content/journal/<slug>.md → <slug>.html
     • the Journal hub                  blog.html
     • the whole sitemap                sitemap.xml

   Publishing a new article is one file: drop a .md into content/journal/
   (copy _TEMPLATE.md), then run this. The hub, the category grouping, the
   related-articles blocks, the JSON-LD and the sitemap all follow.

     node scripts/build-journal.js            write
     node scripts/build-journal.js --check    exit 1 if the committed output
                                              is out of date (no writes)

   The site has no build step — Vercel serves the repo as-is — so this runs
   on a workstation and its output is committed. scripts/ and content/ are
   both listed in .vercelignore and are never served.

   Re-run it after regenerating product data: the "Shop this guide" cards
   bake in name / price / image from data/product-data.json.
═══════════════════════════════════════════════════ */

const fs = require('fs');
const path = require('path');
const cp = require('child_process');

const { parseYaml, parseFrontMatter, YamlError } = require('./lib/journal/yaml');
const markdown = require('./lib/journal/markdown');
const H = require('./lib/journal/html');

const ROOT = path.resolve(__dirname, '..');
const CONTENT_DIR = path.join(ROOT, 'content');
const ARTICLE_DIR = path.join(CONTENT_DIR, 'journal');
const TPL_DIR = path.join(__dirname, 'templates', 'journal');

const CHECK = process.argv.includes('--check');
const GENERATED_NOTICE = source =>
  `<!-- Generated by scripts/build-journal.js from ${source} — do not edit this file by hand. -->`;

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June',
                'July', 'August', 'September', 'October', 'November', 'December'];

const warnings = [];
const warn = msg => { warnings.push(msg); };

class BuildError extends Error {}

/* ═══════════ small helpers ═══════════ */

const readText = f => fs.readFileSync(f, 'utf8').replace(/^﻿/, '');
const rel = f => path.relative(ROOT, f).split(path.sep).join('/');

/* Fill {{placeholders}}. Every placeholder must have a value, and every value
   must be used — a typo in either direction fails the build. */
function fill(template, vars, label) {
  const seen = new Set();
  const out = template.replace(/\{\{([a-zA-Z0-9_]+)\}\}/g, (_m, key) => {
    if (!(key in vars)) throw new BuildError(`${label}: template asks for {{${key}}}, which the generator does not provide`);
    seen.add(key);
    return vars[key];
  });
  for (const key of Object.keys(vars)) {
    if (!seen.has(key)) throw new BuildError(`${label}: generated {{${key}}} but the template never uses it`);
  }
  /* An optional block that rendered empty leaves its own blank line behind. */
  return out.replace(/\n{3,}/g, '\n\n');
}

/* Indent a multi-line block so it sits correctly inside the template. */
function indent(html, spaces) {
  const pad = ' '.repeat(spaces);
  return String(html)
    .split('\n')
    .map(line => (line.trim() === '' ? '' : pad + line))
    .join('\n');
}

function parseDate(value, where) {
  const s = String(value == null ? '' : value).trim();
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(s);
  if (!m) throw new BuildError(`${where}: expected a date as YYYY-MM-DD, found ${JSON.stringify(s)}`);
  const [, y, mo, d] = m;
  const month = parseInt(mo, 10), day = parseInt(d, 10);
  if (month < 1 || month > 12 || day < 1 || day > 31) throw new BuildError(`${where}: ${s} is not a real date`);
  return {
    iso: s,
    sort: Number(y + mo + d),
    long: `${day} ${MONTHS[month - 1]} ${y}`,
    short: `${day} ${MONTHS[month - 1].slice(0, 3)} ${y}`
  };
}

/* ── lastmod source: the file's last commit date, or its mtime when the
      working tree has uncommitted changes (or git is unavailable). ── */
let dirtyPaths = null;
function loadDirtyPaths() {
  if (dirtyPaths) return dirtyPaths;
  dirtyPaths = new Set();
  try {
    const out = cp.execFileSync('git', ['status', '--porcelain'], { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
    out.split('\n').forEach(line => {
      const p = line.slice(3).trim().replace(/^"|"$/g, '');
      if (p) dirtyPaths.add(p.split(' -> ').pop());
    });
  } catch { /* not a git checkout — fall back to mtimes */ }
  return dirtyPaths;
}

const fileDateCache = new Map();
function fileDate(relPath) {
  if (fileDateCache.has(relPath)) return fileDateCache.get(relPath);
  const abs = path.join(ROOT, relPath);
  let result = null;
  if (!loadDirtyPaths().has(relPath)) {
    try {
      const out = cp.execFileSync('git', ['log', '-1', '--format=%cs', '--', relPath],
        { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
      if (/^\d{4}-\d{2}-\d{2}$/.test(out)) result = out;
    } catch { /* fall through to mtime */ }
  }
  if (!result) {
    try { result = new Date(fs.statSync(abs).mtime).toISOString().slice(0, 10); }
    catch { result = new Date().toISOString().slice(0, 10); }
  }
  fileDateCache.set(relPath, result);
  return result;
}

/* ═══════════ config ═══════════ */

function loadConfig() {
  const file = path.join(CONTENT_DIR, 'site.yml');
  const cfg = parseYaml(readText(file), rel(file), 1);
  for (const key of ['site', 'hub', 'categories', 'article', 'sitemap']) {
    if (!cfg[key]) throw new BuildError(`${rel(file)}: missing "${key}" section`);
  }
  cfg.categoryBySlug = new Map();
  cfg.categories.forEach(cat => {
    if (!cat.slug || !cat.label || !cat.section) {
      throw new BuildError(`${rel(file)}: every category needs slug, label and section`);
    }
    cfg.categoryBySlug.set(cat.slug, cat);
  });
  cfg.origin = String(cfg.site.origin).replace(/\/+$/, '');
  return cfg;
}

const absUrl = (cfg, p) => `${cfg.origin}/${String(p).replace(/^\/+/, '')}`;

/* ═══════════ product catalogue ═══════════ */

const normSku = s => String(s == null ? '' : s).replace(/\s+/g, '').toUpperCase();

function loadCatalogue(cfg) {
  const relSource = cfg.sitemap.products.source;
  const file = path.join(ROOT, relSource);
  const data = JSON.parse(readText(file));
  const products = data.products || [];
  const bySku = new Map();
  const byId = new Map();
  products.forEach(p => {
    byId.set(String(p.id).toUpperCase(), p);
    (p.variants || []).forEach(v => {
      const key = normSku(v.sku);
      if (key && !bySku.has(key)) bySku.set(key, p);
    });
  });
  return { products, bySku, byId, source: relSource };
}

/* ═══════════ articles ═══════════ */

function requireField(data, key, where) {
  const value = data[key];
  if (value === undefined || value === null || String(value).trim() === '') {
    throw new BuildError(`${where}: "${key}" is required in the front matter`);
  }
  return value;
}

function loadArticle(file, cfg) {
  const where = rel(file);
  const { data, body } = parseFrontMatter(readText(file), where);

  const slug = String(data.slug || path.basename(file, '.md')).trim();
  if (!/^[a-z0-9][a-z0-9-]*$/.test(slug)) {
    throw new BuildError(`${where}: slug ${JSON.stringify(slug)} must be lower-case letters, numbers and hyphens`);
  }

  const title = String(requireField(data, 'title', where)).trim();
  const description = String(requireField(data, 'description', where)).trim();
  const categorySlug = String(requireField(data, 'category', where)).trim();
  const category = cfg.categoryBySlug.get(categorySlug);
  if (!category) {
    throw new BuildError(`${where}: unknown category "${categorySlug}" — add it to content/site.yml or use one of: ` +
      [...cfg.categoryBySlug.keys()].join(', '));
  }

  const published = parseDate(requireField(data, 'published', where), `${where} (published)`);
  const updated = data.updated ? parseDate(data.updated, `${where} (updated)`) : published;
  if (updated.sort < published.sort) throw new BuildError(`${where}: "updated" is earlier than "published"`);

  const hero = data.hero || {};
  if (!hero.src) throw new BuildError(`${where}: "hero.src" is required`);
  if (!hero.alt) throw new BuildError(`${where}: "hero.alt" is required — it is the image's accessible name and an SEO signal`);
  const heroFile = path.join(ROOT, String(hero.src));
  const probe = H.imageSize(heroFile);
  if (!probe) {
    throw new BuildError(`${where}: cannot read hero image ${hero.src} — check the path (relative to the site root)`);
  }
  const heroWidth = hero.width || probe.width;
  const heroHeight = hero.height || probe.height;
  if (!heroWidth || !heroHeight) {
    throw new BuildError(`${where}: could not determine the size of ${hero.src} — set hero.width and hero.height`);
  }
  const heroKB = Math.round(probe.bytes / 1024);
  if (heroKB > (cfg.article.heroMaxKB || 300)) {
    warn(`${where}: hero image is ${heroKB} KB (target ${cfg.article.heroMaxKB} KB) — re-export it smaller; it is the LCP element`);
  }

  const words = markdown.wordCount(body);
  const minutes = Math.max(1, Math.round(words / (cfg.article.wordsPerMinute || 200)));
  const readTime = data.readTime ? String(data.readTime) : `${minutes} min read`;

  const subtitle = data.subtitle ? String(data.subtitle).trim() : '';
  const shortTitle = data.shortTitle
    ? String(data.shortTitle).trim()
    : (title.includes(': ') ? title.split(': ')[0] : title);

  const faq = (data.faq || []).map((item, i) => {
    if (!item || !item.q || !item.a) throw new BuildError(`${where}: faq item ${i + 1} needs both "q" and "a"`);
    return { q: String(item.q).trim(), a: String(item.a).trim() };
  });

  return {
    file, where, slug,
    path: `${slug}.html`,
    draft: data.draft === true,
    title, shortTitle, subtitle, description,
    pageTitle: data.pageTitle ? String(data.pageTitle) : `${title} | ${cfg.site.titleSuffix}`,
    ogTitle: data.ogTitle ? String(data.ogTitle) : title,
    ogDescription: String(data.ogDescription || subtitle || description),
    excerpt: String(data.excerpt || subtitle || description),
    keywords: data.keywords ? String(data.keywords) : '',
    category, topic: data.topic ? String(data.topic) : '',
    published, updated, readTime, words,
    hero: {
      src: String(hero.src),
      alt: String(hero.alt).trim(),
      caption: hero.caption ? String(hero.caption) : '',
      width: heroWidth,
      height: heroHeight,
      titleInHero: hero.titleInHero === true
    },
    shop: data.shop || null,
    faq,
    faqHeading: data.faqHeading ? String(data.faqHeading) : 'Frequently Asked Questions',
    cta: data.cta || null,
    body
  };
}

function loadArticles(cfg) {
  if (!fs.existsSync(ARTICLE_DIR)) throw new BuildError(`missing ${rel(ARTICLE_DIR)}`);
  const files = fs.readdirSync(ARTICLE_DIR)
    .filter(f => f.endsWith('.md') && !f.startsWith('_'))
    .sort()
    .map(f => path.join(ARTICLE_DIR, f));

  const all = files.map(f => loadArticle(f, cfg));
  const bySlug = new Map();
  all.forEach(a => {
    if (bySlug.has(a.slug)) throw new BuildError(`${a.where}: slug "${a.slug}" is already used by ${bySlug.get(a.slug).where}`);
    bySlug.set(a.slug, a);
  });

  const published = all.filter(a => !a.draft);
  all.filter(a => a.draft).forEach(a => warn(`${a.where}: draft — not published, not listed, not in the sitemap`));

  /* Newest first; a stable tiebreak keeps output deterministic. */
  published.sort((a, b) => (b.published.sort - a.published.sort) || a.slug.localeCompare(b.slug));
  return published;
}

/* ═══════════ components ═══════════ */

function heroFigure(article) {
  const caption = article.hero.caption
    ? `\n  <figcaption>${H.text(article.hero.caption)}</figcaption>`
    : '';
  return `<figure class="article-hero-img">
  <img src="${H.escapeHtml(article.hero.src)}"
       alt="${H.text(article.hero.alt)}"
       width="${article.hero.width}" height="${article.hero.height}" loading="eager" fetchpriority="high" />${caption}
</figure>`;
}

/* "Shop this guide" — product cards resolved from data/product-data.json.
   Name, price and cover image are baked in at build time; the card links to
   product.html, which owns variants, live stock and Add to Cart. */
function shopSection(article, catalogue) {
  const shop = article.shop;
  if (!shop) return '';
  const items = shop.items || [];
  if (!items.length) throw new BuildError(`${article.where}: "shop" has no items`);

  const cards = items.map((item, i) => {
    const at = `${article.where}: shop item ${i + 1}`;
    if (!item.sku && !item.id) throw new BuildError(`${at} needs a "sku" (or an "id")`);
    const product = item.id
      ? catalogue.byId.get(String(item.id).toUpperCase())
      : catalogue.bySku.get(normSku(item.sku));
    if (!product) {
      throw new BuildError(`${at}: ${item.sku || item.id} is not in ${catalogue.source} — check the SKU`);
    }
    if (!product.inStock) warn(`${at}: ${product.id} (${item.sku || item.id}) is out of stock right now`);

    const name = item.label ? String(item.label) : product.name;
    const cover = (product.images && product.images.cover) || '';
    if (!cover) throw new BuildError(`${at}: ${product.id} has no cover image`);
    const size = /^https?:/i.test(cover) ? null : H.imageSize(path.join(ROOT, cover));
    const dims = size && size.width ? ` width="${size.width}" height="${size.height}"` : '';
    const kicker = item.kicker
      ? `\n        <span class="shop-card__kicker">${H.text(item.kicker)}</span>`
      : '';

    return `    <a class="shop-card" href="product.html?id=${H.escapeHtml(product.id)}">
      <span class="shop-card__media">
        <img src="${H.escapeHtml(cover)}" alt="${H.text(product.name)}"${dims} loading="lazy" decoding="async" />
      </span>
      <span class="shop-card__body">${kicker}
        <span class="shop-card__name">${H.text(name)}</span>
        <span class="shop-card__price">${H.text(product.priceDisplay || '')}</span>
        <span class="shop-card__cta">View product &rarr;</span>
      </span>
    </a>`;
  });

  const eyebrow = shop.eyebrow ? `\n  <p class="shop-guide__eyebrow">${H.text(shop.eyebrow)}</p>` : '';
  const intro = shop.intro ? `\n  <p class="shop-guide__intro">${H.text(shop.intro)}</p>` : '';
  const heading = H.text(shop.heading || 'Shop this guide');

  return `<aside class="shop-guide" aria-label="${H.text(shop.heading || 'Shop this guide')}">${eyebrow}
  <h2 class="shop-guide__title">${heading}</h2>${intro}
  <div class="shop-guide__grid">
${cards.join('\n')}
  </div>
</aside>`;
}

function faqSection(article) {
  if (!article.faq.length) return '';
  const items = article.faq.map(item => {
    const answer = markdown.render(item.a, {}).html.map(block => indent(block, 6)).join('\n');
    return `  <div class="faq-item">
    <h3 class="faq-item__q" id="faq-${H.slugify(item.q)}">${markdown.inline(item.q)}</h3>
    <div class="faq-item__a">
${answer}
    </div>
  </div>`;
  });
  return `<section class="article-faq" aria-labelledby="article-faq-title">
  <h2 class="article-faq__title" id="article-faq-title">${H.text(article.faqHeading)}</h2>
${items.join('\n')}
</section>`;
}

function ctaBlock(article) {
  const cta = article.cta;
  if (!cta) return '';
  for (const key of ['heading', 'href', 'label']) {
    if (!cta[key]) throw new BuildError(`${article.where}: "cta.${key}" is required when a cta block is present`);
  }
  const body = cta.body ? `\n        <p>${H.text(cta.body)}</p>` : '';
  return `
      <!-- ── Closing CTA ── -->
      <div class="article-cta">
        <h3>${H.text(cta.heading)}</h3>${body}
        <a href="${H.escapeHtml(cta.href)}" class="btn btn--gold">${H.text(cta.label)}</a>
      </div>
`;
}

/* The listing card, shared by the hub and by the related-articles block. */
function journalCard(article, headingLevel) {
  const href = H.escapeHtml(article.path);
  return `<article class="journal-card">
  <a href="${href}" class="journal-card__media" aria-label="Read: ${H.text(article.shortTitle)}">
    <img src="${H.escapeHtml(article.hero.src)}"
         alt="${H.text(article.hero.alt)}"
         width="${article.hero.width}" height="${article.hero.height}" loading="lazy" decoding="async" />
  </a>
  <div class="journal-card__body">
    <div class="journal-card__meta">
      <span class="journal-card__tag">${H.text(article.category.label)}</span>
      <span class="sep">&middot;</span>
      <time datetime="${article.published.iso}">${H.text(article.published.short)}</time>
      <span class="sep">&middot;</span>
      <span>${H.text(article.readTime)}</span>
    </div>
    <h${headingLevel} class="journal-card__title">
      <a href="${href}">${H.text(article.title)}</a>
    </h${headingLevel}>
    <p class="journal-card__excerpt">${H.text(article.excerpt)}</p>
    <a href="${href}" class="journal-card__more">Read more &rarr;</a>
  </div>
</article>`;
}

function relatedBlock(article, articles, cfg) {
  const limit = cfg.article.relatedCount || 3;
  const others = articles.filter(a => a.slug !== article.slug);
  const sameCategory = others.filter(a => a.category.slug === article.category.slug);
  const picked = sameCategory.slice(0, limit);
  if (picked.length < limit) {
    others.filter(a => a.category.slug !== article.category.slug)
      .slice(0, limit - picked.length)
      .forEach(a => picked.push(a));
  }
  if (!picked.length) return '';

  const allSameCategory = picked.every(a => a.category.slug === article.category.slug);
  const heading = allSameCategory ? `More in ${article.category.section}` : 'More from the Journal';
  const cards = picked.map(a => indent(journalCard(a, 3), 10)).join('\n');

  return `
    <!-- ═══════════════════ RELATED ARTICLES ═══════════════════ -->
    <section class="article-related" aria-labelledby="article-related-title">
      <div class="article-related__inner">
        <div class="article-related__head">
          <h2 class="article-related__title" id="article-related-title">${H.text(heading)}</h2>
          <a href="blog.html" class="article-related__all">All articles &rarr;</a>
        </div>
        <div class="journal-grid">
${cards}
        </div>
      </div>
    </section>
`;
}

/* ═══════════ JSON-LD ═══════════ */

function jsonLdScript(graph) {
  return indent(JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }, null, 2), 2);
}

function articleGraph(article, cfg) {
  const url = absUrl(cfg, article.path);
  const graph = [
    {
      '@type': 'BlogPosting',
      '@id': `${url}#article`,
      headline: H.plain(H.smartQuotes(article.title)),
      description: H.plain(H.smartQuotes(article.description)),
      image: {
        '@type': 'ImageObject',
        url: absUrl(cfg, article.hero.src),
        width: article.hero.width,
        height: article.hero.height
      },
      datePublished: article.published.iso,
      dateModified: article.updated.iso,
      author: { '@type': 'Organization', name: cfg.site.brand, url: `${cfg.origin}/` },
      publisher: {
        '@type': 'Organization',
        name: cfg.site.brand,
        logo: { '@type': 'ImageObject', url: absUrl(cfg, cfg.site.logo) }
      },
      mainEntityOfPage: { '@type': 'WebPage', '@id': url },
      articleSection: article.category.section,
      inLanguage: 'en-MY',
      wordCount: article.words,
      isPartOf: { '@type': 'Blog', '@id': `${absUrl(cfg, cfg.hub.path)}#blog` },
      breadcrumb: { '@id': `${url}#breadcrumb` }
    },
    {
      '@type': 'BreadcrumbList',
      '@id': `${url}#breadcrumb`,
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: `${cfg.origin}/` },
        { '@type': 'ListItem', position: 2, name: 'Journal', item: absUrl(cfg, cfg.hub.path) },
        { '@type': 'ListItem', position: 3, name: H.plain(H.smartQuotes(article.shortTitle)), item: url }
      ]
    }
  ];
  if (article.keywords) graph[0].keywords = H.plain(H.smartQuotes(article.keywords));

  if (article.faq.length) {
    graph.push({
      '@type': 'FAQPage',
      '@id': `${url}#faq`,
      mainEntity: article.faq.map(item => ({
        '@type': 'Question',
        name: H.plain(H.smartQuotes(item.q)),
        acceptedAnswer: {
          '@type': 'Answer',
          text: H.plain(markdown.render(item.a, {}).html.join(' '))
        }
      }))
    });
  }
  return graph;
}

function hubGraph(articles, cfg) {
  const url = absUrl(cfg, cfg.hub.path);
  return [
    {
      '@type': 'Blog',
      '@id': `${url}#blog`,
      url,
      name: H.plain(cfg.hub.ogTitle || cfg.hub.pageTitle),
      description: H.plain(cfg.hub.description),
      inLanguage: 'en-MY',
      publisher: {
        '@type': 'Organization',
        name: cfg.site.brand,
        logo: { '@type': 'ImageObject', url: absUrl(cfg, cfg.site.logo) }
      },
      blogPost: articles.map(a => ({
        '@type': 'BlogPosting',
        '@id': `${absUrl(cfg, a.path)}#article`,
        headline: H.plain(H.smartQuotes(a.title)),
        url: absUrl(cfg, a.path),
        datePublished: a.published.iso,
        dateModified: a.updated.iso,
        image: absUrl(cfg, a.hero.src),
        articleSection: a.category.section
      }))
    },
    {
      '@type': 'BreadcrumbList',
      '@id': `${url}#breadcrumb`,
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: `${cfg.origin}/` },
        { '@type': 'ListItem', position: 2, name: 'Journal', item: url }
      ]
    }
  ];
}

/* ═══════════ page rendering ═══════════ */

function renderArticle(article, articles, cfg, parts, catalogue) {
  const url = absUrl(cfg, article.path);
  const shop = shopSection(article, catalogue);
  const faq = faqSection(article);

  const markers = { '::shop::': indent(shop, 6), '::faq::': indent(faq, 6) };
  const rendered = markdown.render(article.body, { markers, leadClass: 'article-lead' });

  const blocks = rendered.html.slice();
  /* A component with no marker in the body still gets published — appended
     after the prose, before the closing CTA. */
  if (shop && !rendered.markersUsed.has('::shop::')) blocks.push(indent(shop, 6));
  if (faq && !rendered.markersUsed.has('::faq::')) blocks.push(indent(faq, 6));

  const body = blocks
    .map(block => (block.startsWith(' ') ? block : indent(block, 6)))
    .join('\n\n');

  const shareUrl = encodeURIComponent(url);
  const plainTitle = H.plain(H.smartQuotes(article.title));

  return fill(parts.article, {
    generated: GENERATED_NOTICE(article.where),
    pageTitle: H.text(article.pageTitle),
    description: H.text(article.description),
    keywordsMeta: article.keywords ? `  <meta name="keywords" content="${H.text(article.keywords)}" />` : '',
    canonical: H.escapeHtml(url),
    ogTitle: H.text(article.ogTitle),
    ogDescription: H.text(article.ogDescription),
    ogImage: H.escapeHtml(absUrl(cfg, article.hero.src)),
    ogImageWidth: String(article.hero.width),
    ogImageHeight: String(article.hero.height),
    ogImageAlt: H.text(article.hero.alt),
    published: article.published.iso,
    modified: article.updated.iso,
    section: H.text(article.category.section),
    jsonLd: jsonLdScript(articleGraph(article, cfg)),
    headCommon: parts.headCommon,
    nav: parts.nav,
    footer: parts.footer,
    eyebrow: H.text(article.category.label),
    titleClass: article.hero.titleInHero ? ' visually-hidden' : '',
    title: H.text(article.title),
    subtitleBlock: article.subtitle ? `        <p class="article-head__sub">${H.text(article.subtitle)}</p>` : '',
    publishedLabel: H.text(article.published.long),
    readTime: H.text(article.readTime),
    topicBlock: article.topic
      ? `          <span class="article-meta__dot">&middot;</span>\n          <span>${H.text(article.topic)}</span>`
      : '',
    heroFigure: indent(heroFigure(article), 4),
    breadcrumbLabel: H.text(article.shortTitle),
    body,
    ctaBlock: ctaBlock(article),
    shareUrl,
    shareTextUrl: encodeURIComponent(`${plainTitle} ${url}`),
    shareTitleUrl: encodeURIComponent(H.plain(H.smartQuotes(article.shortTitle))),
    relatedBlock: relatedBlock(article, articles, cfg)
  }, article.where);
}

function renderHub(articles, cfg, parts) {
  const groups = cfg.categories
    .map(cat => ({ cat, posts: articles.filter(a => a.category.slug === cat.slug) }))
    .filter(g => g.posts.length);

  const chips = groups.map(g =>
    `      <a class="journal-cats__chip" href="#${H.escapeHtml(g.cat.slug)}">${H.text(g.cat.section)} ` +
    `<span class="journal-cats__chip--count">${g.posts.length}</span></a>`
  );

  const sections = groups.map(g => {
    const blurb = g.cat.blurb ? `\n        <p class="journal-section__blurb">${H.text(g.cat.blurb)}</p>` : '';
    const cards = g.posts.map(a => indent(journalCard(a, 3), 8)).join('\n');
    return `    <section class="journal-section" id="${H.escapeHtml(g.cat.slug)}" aria-labelledby="${H.escapeHtml(g.cat.slug)}-title">
      <div class="journal-section__head">
        <h2 class="journal-section__title" id="${H.escapeHtml(g.cat.slug)}-title">${H.text(g.cat.section)}</h2>${blurb}
      </div>
      <div class="journal-grid">
${cards}
      </div>
    </section>`;
  });

  const empty = '    <p class="journal-section__blurb">New stories are on the way.</p>';
  const heroImage = cfg.hub.ogImage;
  const heroProbe = H.imageSize(path.join(ROOT, heroImage));
  if (!heroProbe) throw new BuildError(`content/site.yml: cannot read hub.ogImage ${heroImage}`);

  return fill(parts.hub, {
    generated: GENERATED_NOTICE('content/journal/*.md'),
    pageTitle: H.text(cfg.hub.pageTitle),
    description: H.text(cfg.hub.description),
    keywordsMeta: cfg.hub.keywords ? `  <meta name="keywords" content="${H.text(cfg.hub.keywords)}" />` : '',
    canonical: H.escapeHtml(absUrl(cfg, cfg.hub.path)),
    ogTitle: H.text(cfg.hub.ogTitle || cfg.hub.pageTitle),
    ogDescription: H.text(cfg.hub.ogDescription || cfg.hub.description),
    ogImage: H.escapeHtml(absUrl(cfg, heroImage)),
    ogImageWidth: String(heroProbe.width),
    ogImageHeight: String(heroProbe.height),
    ogImageAlt: H.text(`${cfg.site.brand} — ${cfg.hub.heroTitle}`),
    jsonLd: jsonLdScript(hubGraph(articles, cfg)),
    headCommon: parts.headCommon,
    nav: parts.nav,
    footer: parts.footer,
    heroEyebrow: H.text(cfg.hub.heroEyebrow),
    heroTitle: H.text(cfg.hub.heroTitle),
    heroDesc: H.text(cfg.hub.heroDesc),
    chips: chips.length > 1 ? `    <nav class="journal-cats" aria-label="Journal categories">\n${chips.join('\n')}\n    </nav>` : '',
    sections: sections.length ? sections.join('\n\n') : empty
  }, 'blog.html');
}

/* ═══════════ sitemap ═══════════ */

function renderSitemap(articles, cfg, catalogue) {
  const rows = [];
  const push = (loc, lastmod, changefreq, priority) => {
    rows.push(`  <url>
    <loc>${H.escapeHtml(loc)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`);
  };

  const newestArticle = articles.length
    ? articles.reduce((acc, a) => (a.updated.sort > acc.updated.sort ? a : acc), articles[0]).updated.iso
    : fileDate(cfg.hub.path);

  cfg.sitemap.pages.forEach(entry => {
    if (entry.insert === 'journal') {
      push(absUrl(cfg, cfg.hub.path), newestArticle, cfg.hub.changefreq, cfg.hub.priority);
      articles.forEach(a => push(absUrl(cfg, a.path), a.updated.iso, cfg.article.changefreq, cfg.article.priority));
      return;
    }
    if (entry.insert === 'products') {
      const lastmod = fileDate(catalogue.source);
      const p = cfg.sitemap.products;
      catalogue.products.forEach(product => {
        push(absUrl(cfg, p.pattern.replace('{id}', product.id)), lastmod, p.changefreq, p.priority);
      });
      return;
    }
    if (entry.insert) throw new BuildError(`content/site.yml: unknown sitemap insert "${entry.insert}"`);
    const file = entry.file || entry.loc;
    if (!fs.existsSync(path.join(ROOT, file))) {
      throw new BuildError(`content/site.yml: sitemap lists ${entry.loc || file}, which does not exist`);
    }
    push(absUrl(cfg, entry.loc), fileDate(file), entry.changefreq, entry.priority);
  });

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-journal.js — do not edit this file by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${rows.join('\n')}
</urlset>
`;
}

/* ═══════════ orchestration ═══════════ */

function loadParts() {
  const read = name => readText(path.join(TPL_DIR, name)).replace(/\n$/, '');
  return {
    article: readText(path.join(TPL_DIR, 'article.html')),
    hub: readText(path.join(TPL_DIR, 'hub.html')),
    nav: read('partials/nav.html'),
    footer: read('partials/footer.html'),
    headCommon: read('partials/head-common.html')
  };
}

function emit(results, relPath, content) {
  const abs = path.join(ROOT, relPath);
  let existing = null;
  try { existing = readText(abs); } catch { /* new file */ }
  const changed = existing !== content;
  if (changed && !CHECK) fs.writeFileSync(abs, content, 'utf8');
  results.push({ path: relPath, changed, existed: existing !== null });
}

function main() {
  const cfg = loadConfig();
  const catalogue = loadCatalogue(cfg);
  const parts = loadParts();
  const articles = loadArticles(cfg);

  const results = [];
  articles.forEach(article => {
    emit(results, article.path, renderArticle(article, articles, cfg, parts, catalogue));
  });
  emit(results, cfg.hub.path, renderHub(articles, cfg, parts));
  emit(results, cfg.sitemap.path, renderSitemap(articles, cfg, catalogue));

  /* An article file that was renamed or deleted leaves its HTML behind. */
  const live = new Set(articles.map(a => a.path));
  fs.readdirSync(ROOT)
    .filter(f => f.endsWith('.html') && !live.has(f) && f !== cfg.hub.path)
    .forEach(f => {
      const head = readText(path.join(ROOT, f)).slice(0, 400);
      if (head.includes('scripts/build-journal.js')) {
        warn(`${f} was generated by an article that no longer exists — delete it, or restore its .md`);
      }
    });

  const changed = results.filter(r => r.changed);

  if (CHECK) {
    results.forEach(r => console.log(`  ${r.changed ? 'STALE  ' : 'ok     '} ${r.path}`));
    warnings.forEach(w => console.log(`  warn   ${w}`));
    if (changed.length) {
      console.error(`\n${changed.length} file(s) out of date. Run: npm run build:journal`);
      process.exit(1);
    }
    console.log(`\nUp to date — ${articles.length} article(s), ${catalogue.products.length} products.`);
    return;
  }

  results.forEach(r => {
    const label = !r.existed ? 'created' : r.changed ? 'updated' : 'unchanged';
    console.log(`  ${label.padEnd(9)} ${r.path}`);
  });
  warnings.forEach(w => console.log(`  warn      ${w}`));
  console.log(`\n${articles.length} article(s) · ${changed.length} file(s) written · ${warnings.length} warning(s)`);
}

try {
  main();
} catch (err) {
  if (err instanceof BuildError || err instanceof YamlError) {
    console.error(`\nbuild-journal: ${err.message}\n`);
    process.exit(1);
  }
  throw err;
}
